### PR TITLE
Add transpile builtin test

### PR DESCRIPTION
**Pull request by TrySound**
Should we ignore bundle-1/index.js file and rely only on snapshot file? We can add bundles to gitignore.

### CODE REVIEW

**Comment by zindel** [comment]
@TrySound maybe we could create the tempfile for each test right in the helper instead? I.e. never pass `output` to the fpack

**Comment by TrySound** [comment]
@zindel Output has default currently

**Comment by TrySound** [comment]
@zindel Or do you mean generating bundle folder?

**Comment by zindel** [comment]
Yes, exactly. Temporary folder somewhere in the OS TMPDIR, so that we don't care about it at all

**Pull request merged**
