### PR TITLE
Resolve node_modules in parents until --project-root

### PR DESCRIPTION
**Pull request by TrySound**
Added test case and commited changed flow parser stuff which doesn't work for some reason when I run `esy build`.

```
File "Fastpack/jbuild", line 7, characters 123-133:
Error: Library "FlowParser" not found.
Hint: try: jbuilder external-lib-deps --missing @install
File "FastpackUtil/jbuild", line 6, characters 55-65:
Error: Library "FlowParser" not found.
Hint: try: jbuilder external-lib-deps --missing @install
esy-build-package: run ['sandbox-exec' '-f'

                   '/var/folders/45/62sm5z9j7_79q17k3p17xl180000gn/T/a4adba'

                   '/Users/trysound/.esy/3___________________________________________________________
_____/i/opam__slash__jbuilder-1.0.0-beta20-156e51f6/bin/jbuilder'
                        'build']: exited with 1
```

### CODE REVIEW

**Comment by andreypopp** [comment]
Run `make bootstrap` which will init the needed submodules.

**Comment by zindel** [comment]
@TrySound plz remove FlowParser.install and add the dev/ directory with the bundle produced. This way we could check in nothing is changed in the subsequent run

**Comment by TrySound** [comment]
I will rebase

**Comment by zindel** [comment]
@TrySound thank you for dragging it till the end! I love the node-service `module.paths` update! Meging

**Pull request merged**
