### PR TITLE
Configuration file & explain-config command

### PR DESCRIPTION
**Pull request by zindel**
So, this effort is to implement the support of the config file for fastpack. Command-line arguments work reasonably well, but it is really tedious to use those in a cross-platform environment (read, Windows vs. *X). The idea here is to implement very basic JSON config file which effectively mirrors what we've got so far in the CLI. Here are TODO items in no particular order:

- [x] Add CLI argument `--config somefile.json` to read from
- [x] Config is loaded from the first matched source below:
   - [x] `--config config.json`
   - [ ] ~~`package.json/fastpack` section (`package.json` in the current directory)~~
   - [x] `./fastpack.json` if exists
   - [x] empty config
- [x] Support merging of the provided values from both sources: CLI & config file
  - [x] for scalar values (`--no-cache`, `--development`, `--output` etc.): CLI value wins over the config's one
  - [x] for list values (`--node-modules`, `--preprocess`): if config or CLI arguments are specified - those lists are concatenated (CLI one goes first), otherwise the default list is used
  - [x] for `entryPoints`: even this parameter is a list, but the strategy is essentially the same as for the scalar values
- [x] Remove `--postprocess`: it refers to an old implementation of the production mode, which we need to rework anyway
- [x] Remove `--target`: I feel like it was specified incorrectly from the very beginning. It should probably be `Browser | Node | Electron`?
- [x] Add `fpack explain-config` command which will print out the parsed & merged config with required explanation and comments
  - [x] Use `pastel.lib` for terminal colors

### CODE REVIEW

**Comment by TrySound** [comment]
Maybe also "fastpack" field in package.json for those who have enough files in the folder?

**Comment by zindel** [comment]
Thought about it some. What gets the priority in this case (we have 4 sources: `package.json`, `fastpack.json`, CLI, default values)?

**Comment by TrySound** [comment]
Use this for inspiration
https://github.com/davidtheclark/cosmiconfig#cosmiconfig

I think like this
1. CLI to allow override all config options on the fly
2. package.json as project config
3. --config or fastpack.json as external config
4. defaults

**Comment by zindel** [comment]
Agreed

**Comment by andreypopp** [comment]
I vote against `fastpack` field in `package.json` — let's have a single way for fastpack to discover config — via files. We can revisit it later but I think having config in separate files is just more flexible — you can have multiple of them and choose the one via `-c/--config` option. You cannot do anything with `"fastpack"` section in `package.json` — it's just some default location, another one which adds to confusion.

**Pull request merged**
